[package]
name = "vonal-rust"
version = "0.1.0"
authors = ["David Judge <dbiro97@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
freedesktop-desktop-entry = "0.5.0"
regex = "1.6.0"

[dependencies.druid]
git = "https://github.com/linebender/druid"
features = ["svg", "im"]