[package]
name = "vonal"
version = "0.1.0"
edition = "2021"

[dependencies]

# GUI:
egui = "0.19.0"
egui_extras = { version = "0.19.0", features = ["svg"] }
poll-promise = "0.2.0"
egui_glow = { version = "0.19.0", features = ["clipboard", "winit"] }
glutin = "0.29"

# Launcher plugin:
freedesktop-desktop-entry = "0.5.0"
regex = "1.6.0"
