[package]
name = "vonal"
version = "0.1.0"
edition = "2021"
features = ["launcher_plugin", "math_plugin"]
path = "src/vonal_daemon/main.rs"

[[bin]]
name = "vonal"
path = "src/vonal_daemon/main.rs"

[[bin]]
name = "vonalc"
path = "src/vonal_client/main.rs"

[env]
SOCKET_PATH = { value = "vonal.socket" }

[features]
default = ["launcher_plugin", "math_plugin"]
launcher_plugin = ["freedesktop-desktop-entry", "regex"]
math_plugin = []

[dependencies]
egui = "0.19.0"
egui_extras = { version = "0.19.0", features = ["svg"] }
poll-promise = "0.2.0"
egui_glow = { version = "0.19.0", features = ["clipboard", "winit"] }
glutin = "0.29"

# launcher_plugin
freedesktop-desktop-entry = { version = "0.5.0", optional = true }
regex = { version = "1.6.0", optional = true }
