[package]
name = "vonal-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# GUI:
eframe = "0.19.0"
egui_glium = "0.19.0"
egui_extras = { version = "0.19.0", features = ["svg"] }

# Launcher plugin:
freedesktop-desktop-entry = "0.5.0"
regex = "1.6.0"
